package linelength

import (
	"strings"
	"testing"

	"github.com/jeduden/mdsmith/internal/lint"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func fixSource(t *testing.T, r *Rule, src string) string {
	t.Helper()
	f, err := lint.NewFile("test.md", []byte(src))
	require.NoError(t, err)
	return string(r.Fix(f))
}

func TestFix_DisabledIsNoOp(t *testing.T) {
	r := &Rule{Max: 40} // Reflow defaults to false
	src := "This line is deliberately made long enough to exceed the forty character limit here.\n"
	if got := fixSource(t, r, src); got != src {
		t.Errorf("Fix with reflow off changed source:\n%q", got)
	}
}

func TestFix_BasicReflow(t *testing.T) {
	r := &Rule{Max: 40, Reflow: true}
	src := "# Title\n\nThe quick brown fox jumps over the lazy dog and then keeps running for a while."
	want := "# Title\n\nThe quick brown fox jumps over the lazy\ndog and then keeps running for a while."
	got := fixSource(t, r, src)
	assert.Equal(t, want, got)
	for _, line := range strings.Split(got, "\n") {
		assert.LessOrEqual(t, len(line), 40, "line exceeds width: %q", line)
	}
}

func TestFix_Idempotent(t *testing.T) {
	r := &Rule{Max: 40, Reflow: true}
	src := "The quick brown fox jumps over the lazy dog and then keeps running for a while longer."
	once := fixSource(t, r, src)
	twice := fixSource(t, r, once)
	assert.Equal(t, once, twice, "reflow is not a fixpoint")
}

func TestFix_ShortParagraphUntouched(t *testing.T) {
	r := &Rule{Max: 80, Reflow: true}
	src := "Short and sweet.\n\nAlso short.\n"
	if got := fixSource(t, r, src); got != src {
		t.Errorf("Fix reflowed paragraphs with no long line:\n%q", got)
	}
}

func TestFix_TwoParagraphsOnlyLongOne(t *testing.T) {
	r := &Rule{Max: 40, Reflow: true}
	src := "Short paragraph here.\n\n" +
		"The quick brown fox jumps over the lazy dog and then keeps running for a while."
	got := fixSource(t, r, src)
	assert.True(t, strings.HasPrefix(got, "Short paragraph here.\n\n"),
		"short paragraph should be preserved verbatim: %q", got)
	for _, line := range strings.Split(got, "\n") {
		assert.LessOrEqual(t, len(line), 40, "line exceeds width: %q", line)
	}
}

func TestFix_AbbreviationKeptWithFollowingWord(t *testing.T) {
	r := &Rule{Max: 12, Reflow: true}
	src := "We met Dr. Watson today."
	// "Dr. Watson" is one unit; it does not fit after "We met", so it
	// wraps whole onto its own line.
	want := "We met\nDr. Watson\ntoday."
	got := fixSource(t, r, src)
	assert.Equal(t, want, got)
	for _, line := range strings.Split(got, "\n") {
		assert.False(t, strings.HasSuffix(line, "Dr."),
			"line must not end with the abbreviation Dr.: %q", line)
	}
}

func TestFix_CodeSpanPreservedAtomically(t *testing.T) {
	r := &Rule{Max: 40, Reflow: true}
	src := "This sentence uses `a  b  c` inline and runs well past the forty char width limit."
	got := fixSource(t, r, src)
	assert.Contains(t, got, "`a  b  c`",
		"code span internal spacing must be preserved: %q", got)
}

func TestFix_HeadingNotReflowed(t *testing.T) {
	r := &Rule{Max: 30, Reflow: true}
	src := "# This is a fairly long heading that exceeds the configured width\n"
	if got := fixSource(t, r, src); got != src {
		t.Errorf("heading must not be reflowed:\n%q", got)
	}
}

func TestFix_ListItemNotReflowed(t *testing.T) {
	r := &Rule{Max: 40, Reflow: true}
	src := "- this is a long list item that definitely exceeds the configured maximum width here\n"
	if got := fixSource(t, r, src); got != src {
		t.Errorf("list item must not be reflowed (top-level only):\n%q", got)
	}
}

func TestFix_TableNotReflowed(t *testing.T) {
	r := &Rule{Max: 40, Reflow: true}
	src := "| col a | col b that is really long enough to exceed the maximum width configured |\n"
	if got := fixSource(t, r, src); got != src {
		t.Errorf("table row must not be reflowed:\n%q", got)
	}
}

func TestFix_HardLineBreakParagraphSkipped(t *testing.T) {
	r := &Rule{Max: 40, Reflow: true}
	// First line ends with a backslash hard break; the paragraph must be
	// left untouched so the intentional break survives.
	src := "This first line is quite long and ends with a hard break here now\\\nsecond line."
	if got := fixSource(t, r, src); got != src {
		t.Errorf("paragraph with hard break must be skipped:\n%q", got)
	}
}

func TestFix_GeneratedSectionSkipped(t *testing.T) {
	r := &Rule{Max: 40, Reflow: true}
	src := "The quick brown fox jumps over the lazy dog and then keeps running for a while."
	f, err := lint.NewFile("test.md", []byte(src))
	require.NoError(t, err)
	// Mark the whole document as a generated range: the host file must
	// not rewrite generated bytes.
	f.GeneratedRanges = []lint.LineRange{{From: 1, To: 1}}
	if got := string(r.Fix(f)); got != src {
		t.Errorf("paragraph inside a generated range must be skipped:\n%q", got)
	}
}

func TestFix_TrailingNewlinePreserved(t *testing.T) {
	r := &Rule{Max: 40, Reflow: true}
	src := "The quick brown fox jumps over the lazy dog and then keeps running for a while.\n"
	got := fixSource(t, r, src)
	assert.True(t, strings.HasSuffix(got, "\n"), "trailing newline must be preserved")
	assert.False(t, strings.HasSuffix(got, "\n\n"), "no spurious trailing blank line")
}

func TestFix_CodeBlockNotReflowed(t *testing.T) {
	r := &Rule{Max: 40, Reflow: true}
	src := "```\nthis is a long line inside a fenced code block that exceeds the configured width\n```\n"
	if got := fixSource(t, r, src); got != src {
		t.Errorf("code block content must not be reflowed:\n%q", got)
	}
}
