package release

import (
	"bytes"
	"fmt"
	"path/filepath"
)

// flatpakAppID is the reverse-DNS app id. It doubles as the manifest
// basename and the install/run handle (`flatpak run
// io.github.jeduden.mdsmith`).
const flatpakAppID = "io.github.jeduden.mdsmith"

// flatpakRuntimeVersion pins the org.freedesktop runtime/SDK branch
// the bundle builds and runs against. Bump it in lock-step with a
// freedesktop runtime end-of-life.
const flatpakRuntimeVersion = "24.08"

// flatpakBuild maps a Flatpak arch to the Linux release binary it
// ships. Flatpak is Linux-only, so this is the linux subset of the
// build matrix in .github/workflows/release.yml. CI bundles x86_64
// only (flatpak-builder targets the runner's native arch); the
// aarch64 source keeps the manifest buildable on an arm64 host.
type flatpakBuild struct {
	Asset string // release-asset basename (e.g. "mdsmith-linux-arm64")
	Arch  string // flatpak arch: "aarch64" | "x86_64"
}

var flatpakBuilds = []flatpakBuild{
	{"mdsmith-linux-arm64", "aarch64"},
	{"mdsmith-linux-amd64", "x86_64"},
}

// BuildFlatpak stages the flatpak-builder manifest for flatpakAppID
// and the Linux release binaries it references into outDir, reading
// the binaries from artifactsDir. The release.yml `flatpak` job then
// runs flatpak-builder against the manifest and `flatpak
// build-bundle` to produce the single-file .flatpak attached to the
// GitHub release.
//
// The manifest uses local `path:` sources, not release-download
// URLs: the job builds the bundle from the freshly built binaries
// before the release is published, so there is no download URL to
// pin yet. Each binary is copied next to the manifest so
// flatpak-builder resolves its `path:` relative to the manifest
// directory. Every referenced binary must exist in artifactsDir; a
// missing one fails the step with nothing staged.
func (t *Toolkit) BuildFlatpak(artifactsDir, outDir string) error {
	// Read every binary before writing anything, so a missing asset
	// fails the step with a clean (un-created) out-dir.
	bins := make([][]byte, len(flatpakBuilds))
	for i, fb := range flatpakBuilds {
		data, err := t.fs.ReadFile(filepath.Join(artifactsDir, fb.Asset))
		if err != nil {
			return fmt.Errorf("read %s: %w", fb.Asset, err)
		}
		bins[i] = data
	}
	if err := t.fs.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	for i, fb := range flatpakBuilds {
		if err := t.fs.WriteFile(
			filepath.Join(outDir, fb.Asset), bins[i], 0o755); err != nil {
			return fmt.Errorf("stage %s: %w", fb.Asset, err)
		}
	}
	if err := t.fs.WriteFile(
		filepath.Join(outDir, flatpakAppID+".yml"),
		[]byte(renderFlatpakManifest()), 0o644); err != nil {
		return fmt.Errorf("write manifest: %w", err)
	}
	return nil
}

// BuildFlatpak delegates to a default-OS Toolkit (see Stamp).
func BuildFlatpak(artifactsDir, outDir string) error {
	return New().BuildFlatpak(artifactsDir, outDir)
}

// renderFlatpakManifest builds the flatpak-builder manifest. The app
// is a prebuilt binary, so the single module has no compile step:
// one `file` source per arch installs the matching staged binary as
// /app/bin/mdsmith. Sources are local paths (resolved next to the
// manifest), so the bundle builds from the freshly built binaries
// without waiting on the GitHub release that will host it. No
// AppStream metainfo is emitted — a self-hosted CLI bundle is
// installed by file, not listed in a store.
func renderFlatpakManifest() string {
	var buf bytes.Buffer
	buf.WriteString("# Generated by `mdsmith-release build-flatpak`. Do not edit by hand.\n")
	buf.WriteString("app-id: " + flatpakAppID + "\n")
	buf.WriteString("runtime: org.freedesktop.Platform\n")
	fmt.Fprintf(&buf, "runtime-version: '%s'\n", flatpakRuntimeVersion)
	buf.WriteString("sdk: org.freedesktop.Sdk\n")
	buf.WriteString("command: mdsmith\n")
	// A Markdown linter reads whatever repository the user points it
	// at, which can live anywhere on disk; a narrower grant would
	// hide the files it checks.
	buf.WriteString("finish-args:\n")
	buf.WriteString("  - --filesystem=host\n")
	buf.WriteString("modules:\n")
	buf.WriteString("  - name: mdsmith\n")
	buf.WriteString("    buildsystem: simple\n")
	buf.WriteString("    build-commands:\n")
	buf.WriteString("      - install -Dm755 mdsmith /app/bin/mdsmith\n")
	buf.WriteString("    sources:\n")
	for _, fb := range flatpakBuilds {
		buf.WriteString("      - type: file\n")
		buf.WriteString("        only-arches:\n")
		fmt.Fprintf(&buf, "          - %s\n", fb.Arch)
		fmt.Fprintf(&buf, "        path: %s\n", fb.Asset)
		buf.WriteString("        dest-filename: mdsmith\n")
	}
	return buf.String()
}
