// Package release: parity.go renders the table of rules the built-in
// `parity` convention disables into a single fragment that both the
// conventions reference and the benchmark page <?include?>.
//
// Source of truth: the `parity` convention in
// internal/convention/convention.go (which rules) and the rule
// registry (each rule's MDS id and its mdsmith default-enabled state).
// Nothing here is hand-maintained: add or drop a rule in the
// convention and `mdsmith-release sync-parity-rules` re-emits the
// fragment, so the convention, the benchmark profile, and the prose
// docs can never drift.
//
// The fragment carries no front matter or heading so it splices
// cleanly into a host document; it lives under docs/research/ where
// the heading and cross-file rules step aside, and `mdsmith fix`
// re-splices it into each host on demand.
package release

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"github.com/jeduden/mdsmith/internal/convention"
	"github.com/jeduden/mdsmith/internal/rule"
)

// ParityRulesFragmentFile is the path, relative to the repo root, of
// the generated parity-rules fragment. Both
// docs/reference/conventions.md and
// docs/research/benchmarks/README.md include it.
const ParityRulesFragmentFile = "docs/research/benchmarks/parity-rules.fragment.md"

const parityFragmentComment = "<!-- Generated by " +
	"`mdsmith-release sync-parity-rules` from the parity\n" +
	"convention in internal/convention/convention.go. Do not edit by hand;\n" +
	"re-run that command (then `mdsmith fix`) to refresh. -->\n"

// RenderParityRulesFragment builds the parity-rules fragment from the
// `parity` convention and the rule registry.
func RenderParityRulesFragment() (string, error) {
	return renderConventionDisableTable("parity", rule.ByName)
}

// renderConventionDisableTable renders the disabled-rules fragment for
// the named convention. Rows are sorted by MDS id. byName resolves a
// rule name to its registered rule (rule.ByName in production);
// injecting it keeps the registry dependency testable. It errors when
// the convention is unknown, or names a rule byName cannot resolve, so
// a rename surfaces loudly instead of silently dropping a row.
func renderConventionDisableTable(
	name string, byName func(string) rule.Rule,
) (string, error) {
	conv, err := convention.Lookup(name, nil)
	if err != nil {
		return "", fmt.Errorf("looking up %q convention: %w", name, err)
	}

	type prow struct{ id, label, def string }
	prows := make([]prow, 0, len(conv.Rules))
	for ruleName := range conv.Rules {
		r := byName(ruleName)
		if r == nil {
			return "", fmt.Errorf(
				"convention %q names rule %q, which is not registered",
				name, ruleName)
		}
		def := "default"
		if d, ok := r.(rule.Defaultable); ok && !d.EnabledByDefault() {
			def = "opt-in"
		}
		prows = append(prows, prow{id: r.ID(), label: r.ID() + " " + ruleName, def: def})
	}
	sort.Slice(prows, func(i, j int) bool { return prows[i].id < prows[j].id })

	rows := make([][]string, 0, len(prows))
	for _, p := range prows {
		rows = append(rows, []string{p.label, p.def})
	}

	var buf bytes.Buffer
	buf.WriteString(parityFragmentComment)
	buf.WriteByte('\n')
	writePaddedTable(&buf, []string{"Rule", "Default in mdsmith"}, rows)
	return buf.String(), nil
}

// ApplyParityRulesFragment regenerates the fragment file. It reports
// whether the file changed.
func ApplyParityRulesFragment(root string) (bool, error) {
	return applyParityRulesFragment(root, RenderParityRulesFragment)
}

// applyParityRulesFragment is ApplyParityRulesFragment with the
// renderer injected, so the render-error branch is drivable in tests.
func applyParityRulesFragment(root string, render func() (string, error)) (bool, error) {
	want, err := render()
	if err != nil {
		return false, err
	}
	path := filepath.Join(root, ParityRulesFragmentFile)
	have, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return false, fmt.Errorf("reading existing fragment: %w", err)
	}
	if string(have) == want {
		return false, nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, fmt.Errorf("creating output dir: %w", err)
	}
	if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
		return false, fmt.Errorf("writing parity-rules fragment: %w", err)
	}
	return true, nil
}

// CheckParityRulesFragment returns a non-empty drift message when the
// committed fragment differs from the freshly rendered one.
func CheckParityRulesFragment(root string) (string, error) {
	return checkParityRulesFragment(root, RenderParityRulesFragment)
}

// checkParityRulesFragment is CheckParityRulesFragment with the
// renderer injected, so the render-error branch is drivable in tests.
func checkParityRulesFragment(root string, render func() (string, error)) (string, error) {
	want, err := render()
	if err != nil {
		return "", err
	}
	path := filepath.Join(root, ParityRulesFragmentFile)
	have, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("reading existing fragment: %w", err)
	}
	if string(have) == want {
		return "", nil
	}
	return fmt.Sprintf(
		"%s is out of sync with the parity convention.\n"+
			"Run: mdsmith-release sync-parity-rules\n",
		ParityRulesFragmentFile), nil
}
