// Package release: parity.go renders one rule table per <linter>-parity
// convention into a single fragment that both the conventions reference
// and the benchmark page <?include?>.
//
// Source of truth: the <linter>-parity conventions in
// internal/convention/convention.go (which rules each enables and
// disables) and the rule registry (each rule's MDS id and its mdsmith
// default-enabled state). Nothing here is hand-maintained: change a
// convention and `mdsmith-release sync-parity-rules` re-emits the
// fragment, so the conventions, the benchmark profiles, and the prose
// docs can never drift.
//
// The fragment carries no front matter or heading so it splices
// cleanly into a host document; it lives under docs/research/ where
// the heading and cross-file rules step aside, and `mdsmith fix`
// re-splices it into each host on demand.
package release

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/mattn/go-runewidth"

	"github.com/jeduden/mdsmith/internal/convention"
	"github.com/jeduden/mdsmith/internal/rule"
)

// ParityRulesFragmentFile is the path, relative to the repo root, of
// the generated parity-rules fragment. Both
// docs/reference/conventions.md and
// docs/research/benchmarks/README.md include it.
const ParityRulesFragmentFile = "docs/research/benchmarks/parity-rules.fragment.md"

// parityConventions are the per-linter parity conventions the fragment
// documents, in benchmark-narrative order (smallest default rule set
// first).
var parityConventions = []string{
	"gomarklint-parity",
	"mado-parity",
	"rumdl-parity",
	"markdownlint-parity",
}

const parityFragmentComment = "<!-- Generated by " +
	"`mdsmith-release sync-parity-rules` from the\n" +
	"<linter>-parity conventions in internal/convention/convention.go. Do not\n" +
	"edit by hand; re-run that command (then `mdsmith fix`) to refresh. -->\n"

// RenderParityRulesFragment builds the parity-rules fragment: one
// labeled rule table per <linter>-parity convention.
func RenderParityRulesFragment() (string, error) {
	return renderParityFamilyFragment(rule.ByName)
}

// renderParityFamilyFragment renders one table per parity convention,
// in parityConventions order. byName resolves a rule name to its
// registered rule (rule.ByName in production); injecting it keeps the
// registry dependency testable.
func renderParityFamilyFragment(
	byName func(string) rule.Rule,
) (string, error) {
	var buf bytes.Buffer
	buf.WriteString(parityFragmentComment)
	for _, name := range parityConventions {
		buf.WriteByte('\n')
		if err := renderConventionRuleTable(&buf, name, byName); err != nil {
			return "", err
		}
	}
	return buf.String(), nil
}

// renderConventionRuleTable writes one convention's preset as a labeled
// pair of GFM tables: the mdsmith opt-in rules it ENABLES (turns on for
// peer parity) and the mdsmith defaults it DISABLES (the peer does not
// run them). Rows in each table are sorted by MDS id. Splitting the two
// keeps each table within the table-row limit and makes the enable vs
// disable intent explicit. It errors when the convention is unknown, or
// names a rule byName cannot resolve, so a rename surfaces loudly
// instead of silently dropping a row.
func renderConventionRuleTable(
	buf *bytes.Buffer, name string, byName func(string) rule.Rule,
) error {
	conv, err := convention.Lookup(name, nil)
	if err != nil {
		return fmt.Errorf("looking up %q convention: %w", name, err)
	}

	type prow struct{ id, label string }
	var enabled, disabled []prow
	for ruleName, p := range conv.Rules {
		r := byName(ruleName)
		if r == nil {
			return fmt.Errorf(
				"convention %q names rule %q, which is not registered",
				name, ruleName)
		}
		row := prow{id: r.ID(), label: r.ID() + " " + ruleName}
		if p.Enabled {
			enabled = append(enabled, row)
		} else {
			disabled = append(disabled, row)
		}
	}
	byID := func(rows []prow) {
		sort.Slice(rows, func(i, j int) bool { return rows[i].id < rows[j].id })
	}
	byID(enabled)
	byID(disabled)
	toTable := func(rows []prow) [][]string {
		out := make([][]string, 0, len(rows))
		for _, r := range rows {
			out = append(out, []string{r.label})
		}
		return out
	}

	fmt.Fprintf(buf,
		"**`%s`** — enables %d opt-in rules, disables %d defaults:\n\n",
		name, len(enabled), len(disabled))
	buf.WriteString("Enabled opt-in rules:\n\n")
	writePaddedTable(buf, []string{"Rule"}, toTable(enabled))
	buf.WriteString("\nDisabled defaults:\n\n")
	writePaddedTable(buf, []string{"Rule"}, toTable(disabled))
	return nil
}

// ApplyParityRulesFragment regenerates the fragment file. It reports
// whether the file changed.
func ApplyParityRulesFragment(root string) (bool, error) {
	return applyParityRulesFragment(root, RenderParityRulesFragment)
}

// applyParityRulesFragment is ApplyParityRulesFragment with the
// renderer injected, so the render-error branch is drivable in tests.
func applyParityRulesFragment(root string, render func() (string, error)) (bool, error) {
	want, err := render()
	if err != nil {
		return false, err
	}
	path := filepath.Join(root, ParityRulesFragmentFile)
	have, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return false, fmt.Errorf("reading existing fragment: %w", err)
	}
	if string(have) == want {
		return false, nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, fmt.Errorf("creating output dir: %w", err)
	}
	if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
		return false, fmt.Errorf("writing parity-rules fragment: %w", err)
	}
	return true, nil
}

// CheckParityRulesFragment returns a non-empty drift message when the
// committed fragment differs from the freshly rendered one.
func CheckParityRulesFragment(root string) (string, error) {
	return checkParityRulesFragment(root, RenderParityRulesFragment)
}

// checkParityRulesFragment is CheckParityRulesFragment with the
// renderer injected, so the render-error branch is drivable in tests.
func checkParityRulesFragment(root string, render func() (string, error)) (string, error) {
	want, err := render()
	if err != nil {
		return "", err
	}
	path := filepath.Join(root, ParityRulesFragmentFile)
	have, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("reading existing fragment: %w", err)
	}
	if string(have) == want {
		return "", nil
	}
	return fmt.Sprintf(
		"%s is out of sync with the parity conventions.\n"+
			"Run: mdsmith-release sync-parity-rules\n",
		ParityRulesFragmentFile), nil
}

// writePaddedTable writes a GFM table to buf with column widths
// computed from the widest cell in each column (using Unicode
// rune widths so multi-byte characters align correctly), floored
// at three. Each separator cell is a run of dashes as wide as its
// column, so the floor guarantees at least "---" — matching
// internal/rules/tablefmt and the cross-flavor minimum that
// markdown-it and pandoc require.
func writePaddedTable(
	buf *bytes.Buffer, headers []string, rows [][]string,
) {
	widths := make([]int, len(headers))
	for i, h := range headers {
		widths[i] = runewidth.StringWidth(h)
	}
	for _, row := range rows {
		for i, c := range row {
			if w := runewidth.StringWidth(c); w > widths[i] {
				widths[i] = w
			}
		}
	}
	// Floor each column at three so every separator cell renders at
	// least "---", matching internal/rules/tablefmt and the
	// cross-flavor minimum markdown-it and pandoc require.
	for i := range widths {
		if widths[i] < 3 {
			widths[i] = 3
		}
	}
	// Header row.
	for i, h := range headers {
		if i == 0 {
			buf.WriteByte('|')
		}
		buf.WriteByte(' ')
		buf.WriteString(h)
		buf.WriteString(strings.Repeat(" ",
			widths[i]-runewidth.StringWidth(h)))
		buf.WriteString(" |")
	}
	buf.WriteByte('\n')
	// Separator row.
	for i := range headers {
		if i == 0 {
			buf.WriteByte('|')
		}
		buf.WriteByte(' ')
		buf.WriteString(strings.Repeat("-", widths[i]))
		buf.WriteString(" |")
	}
	buf.WriteByte('\n')
	// Body rows.
	for _, row := range rows {
		for i, c := range row {
			if i == 0 {
				buf.WriteByte('|')
			}
			buf.WriteByte(' ')
			buf.WriteString(c)
			buf.WriteString(strings.Repeat(" ",
				widths[i]-runewidth.StringWidth(c)))
			buf.WriteString(" |")
		}
		buf.WriteByte('\n')
	}
}
