package integration

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jeduden/mdsmith/internal/config"
	"github.com/jeduden/mdsmith/internal/fix"
	"github.com/jeduden/mdsmith/internal/rule"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestMultiPassFix_TOCDirective verifies that a single fix run converts
// [TOC] into a populated <?toc?>...<?/toc?> block. MDS035 replaces [TOC]
// with the empty directive in pass 1; MDS038 fills the heading list in pass 2.
func TestMultiPassFix_TOCDirective(t *testing.T) {
	src := "# Document\n\n[TOC]\n\n## Section One\n\n## Section Two\n"

	dir := t.TempDir()
	mdFile := filepath.Join(dir, "doc.md")
	require.NoError(t, os.WriteFile(mdFile, []byte(src), 0o644))

	cfg := &config.Config{
		Rules: map[string]config.RuleCfg{
			"toc-directive": {Enabled: true},
			"toc":           {Enabled: true},
		},
	}

	fixer := &fix.Fixer{
		Config: cfg,
		Rules:  rule.All(),
	}

	result := fixer.Fix([]string{mdFile})
	require.Empty(t, result.Errors, "unexpected errors: %v", result.Errors)

	got, err := os.ReadFile(mdFile)
	require.NoError(t, err)

	content := string(got)
	assert.Contains(t, content, "<?toc?>", "toc directive start marker present")
	assert.Contains(t, content, "<?/toc?>", "toc directive end marker present")
	assert.Contains(t, content, "- [Section One](#section-one)", "heading link present")
	assert.Contains(t, content, "- [Section Two](#section-two)", "heading link present")
	assert.NotContains(t, content, "\n[TOC]\n", "original TOC token replaced")
}

// TestMultiPassFix_CrossFileCatalogIncludeCascade reproduces the
// merge-queue CI-only failure: a file that <?include?>s a second file
// whose body is itself generated by <?catalog?> from a third file.
// When the includer sorts before the catalog host, a single workspace
// sweep embeds the stale host and never revisits the includer — so
// `mdsmith fix .` reports unfixed=0 while a following `mdsmith check .`
// flags the includer as MDS021 "generated section is out of date".
// This is exactly what bounced PR #432 in the queue: the pre-merge
// hook's `mdsmith fix .` left .github/copilot-instructions.md and
// AGENTS.md (both include CLAUDE.md, whose body carries a <?catalog?>)
// stale. A single fix invocation must converge the whole cascade.
func TestMultiPassFix_CrossFileCatalogIncludeCascade(t *testing.T) {
	dir := t.TempDir()

	// Basename sort order is a_top < m_mid < z_leaf, so the includer
	// (a_top) is processed before the catalog host (m_mid) in one
	// sweep — the ordering that triggers the bug.
	leaf := filepath.Join(dir, "z_leaf.md")
	mid := filepath.Join(dir, "m_mid.md")
	top := filepath.Join(dir, "a_top.md")

	writeLeaf := func(summary string) {
		src := "---\ntitle: Leaf\nsummary: " + summary + "\n---\n# Leaf\n\nbody\n"
		require.NoError(t, os.WriteFile(leaf, []byte(src), 0o644))
	}
	writeLeaf("SUMMARY_V1")

	// m_mid mirrors CLAUDE.md: a host whose body is generated from a
	// sibling file via <?catalog?>.
	require.NoError(t, os.WriteFile(mid, []byte(
		"# Mid\n\n"+
			"<?catalog\nglob: \"z_leaf.md\"\nrow: \"- {summary}\"\n?>\n"+
			"<?/catalog?>\n"), 0o644))

	// a_top mirrors AGENTS.md / copilot-instructions.md: it embeds the
	// catalog host wholesale via <?include?>.
	require.NoError(t, os.WriteFile(top, []byte(
		"# Top\n\n"+
			"<?include\nfile: m_mid.md\n?>\n"+
			"<?/include?>\n"), 0o644))

	cfg := &config.Config{
		Rules: map[string]config.RuleCfg{
			"include": {Enabled: true},
			"catalog": {Enabled: true},
		},
	}
	fixer := &fix.Fixer{Config: cfg, Rules: rule.All()}

	// Walk order: the includer precedes the catalog host.
	paths := []string{top, mid, leaf}

	// Establish a converged baseline. This loop converges with or
	// without the workspace fixpoint under test, so the baseline does
	// not presuppose the fix.
	for i := 0; i < 10; i++ {
		res := fixer.Fix(paths)
		require.Empty(t, res.Errors, "unexpected errors during baseline setup: %v", res.Errors)
		b, err := os.ReadFile(top)
		require.NoError(t, err)
		if strings.Contains(string(b), "SUMMARY_V1") {
			break
		}
	}
	base, err := os.ReadFile(top)
	require.NoError(t, err)
	require.Contains(t, string(base), "SUMMARY_V1",
		"baseline did not converge (test setup)")

	// Simulate the merge changing the catalog's source file.
	writeLeaf("SUMMARY_V2")

	// A SINGLE fix invocation must propagate the change through the
	// catalog host and into the includer.
	result := fixer.Fix(paths)
	require.Empty(t, result.Errors, "unexpected errors: %v", result.Errors)

	got, err := os.ReadFile(top)
	require.NoError(t, err)
	assert.Contains(t, string(got), "SUMMARY_V2",
		"a_top.md still embeds the stale catalog after one fix run — "+
			"the include→catalog cascade did not converge in a single workspace pass")
	assert.NotContains(t, string(got), "SUMMARY_V1",
		"a_top.md still carries the pre-merge catalog summary")
}
